# Generated by Django 6.0 on 2026-01-19 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='return_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
