# Generated by Django 6.0 on 2026-01-20 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0002_order_is_approved_order_return_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='return_date',
        ),
    ]
