# Generated by Django 6.0.1 on 2026-01-22 14:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refectory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichaalmoco',
            name='matricula',
        ),
        migrations.AddField(
            model_name='fichaalmoco',
            name='aluno',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fichaalmoco',
            name='ficha_numero',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fichaalmoco',
            name='hora_uso',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fichaalmoco',
            name='token',
            field=models.CharField(default=uuid.uuid4, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='fichaalmoco',
            name='data',
            field=models.DateField(),
        ),
    ]
