# Generated by Django 6.0.1 on 2026-01-27 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refectory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='invalidated_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
    ]
