# Generated by Django 6.0.1 on 2026-01-27 03:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refectory', '0002_token_invalidated_reason_token_is_valid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='uuid',
        ),
        migrations.AlterField(
            model_name='token',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
