# Generated by Django 6.0.1 on 2026-01-22 15:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refectory', '0002_remove_fichaalmoco_matricula_fichaalmoco_aluno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichaalmoco',
            name='ficha_numero',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fichaalmoco',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
